name: Build and Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Package application
        run: |
          mkdir -p build
          zip -r build/deployment-package.zip src/ requirements.txt
          
      - name: Verify deployment package
        run: |
          if [ -f build/deployment-package.zip ]; then
            echo "Deployment package found."
            pwd
            ls
            ls -l build/deployment-package.zip
          else
            echo "Deployment package not found!"
            exit 1
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check Package
        run: |
          ls
          pwd
          zip 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region us-east-1

      - name: Create build directory
        run: |
          mkdir -p build

      - name: Package lambda_function.py
        run: |
          zip -r build/lambda-package.zip lambda_function.py

      - name: List files in build directory
        run: |
          ls -l build/

      - name: Deploy to AWS Lambda
        run: |
          pwd
          ls
          cd build
          ls
          aws lambda update-function-code \
           --function-name my-lambda-function \
           --zip-file fileb://lambda-package.zip \
           --region us-east-1
